### PR TITLE
Python2.7 support

### PR DESCRIPTION
**Pull request by alexole**
Comes with the fixes in zalando-stups/stups-cli-support#8

### CODE REVIEW

**Comment by hjacobs** [comment]
Can you add Python 2.7 to `.travis.yaml` to check on Travis CI?

**Comment by alexole** [comment]
Done, but it has a  zalando-stups/stups-cli-support#8 dependency which will cause the error, the fix was provided as a PR

**Comment by alexole** [comment]
Any thoughts on this?

**Comment by hjacobs** [comment]
As discussed offline, we won't support Python 2.7. You can always call the CLI tools via `subprocess` if really needed.

**Pull request closed without merging**
